# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

author: Veronica Gurgel
title: Veronica T. Gurgel – Psicologia Clínica
subTitle: Psicóloga Clínica – CRP 05/62394
email: veronicagurgel.psi@gmail.com
telephone: (21) 99534-2397
whatsappMessage: Oi, encontrei suas informações de whatsapp no seu site.
description: >- # this means to ignore newlines until "baseurl:"
  Doutora em Psicologia. Possui experiência em consultório particular com foco no público adulto e adolescente. Realiza atendimentos individuais, de forma online.
# baseurl: "/vero-jekyll" # the subpath of your site, e.g. /blog
# url: "localhost:5500" # the base hostname & protocol for your site, e.g. http://example.com
lang: pt-BR
google_analytics: G-45G3NLGY3E
google_tagmanager: GTM-PBQTMCQ

show_excerpts: true

linkedin_username: veronica-gurgel-82a99a110
lattes_username: 9545542889673896
# Build settings
theme: minima

minima:
  date_format: "%-d %b, %Y"

plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
